name: 'NPM publish beta'

on:
  workflow_run:
    workflows: [CI, Pre-release]
    types:
      - completed
  release:
    types: [prereleased]

jobs:
  publish-beta:
    name: 'Puplish beta version to npm'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Setup node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'yarn'

      - name: 'Install dependencies'
        run: yarn install

      - name: Build
        run: yarn build

      - name: 'Set npm auth token'
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > ~/.npmrc

      - name: 'Publish to npm'
        run: npm publish ./dist --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
