name: 'Release'

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
  push:
    branches:
      - 'main'
      - '3.0.0-beta'

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Setup node.js'
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: 'Install dependencies'
        run: yarn install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: npx semantic-release
