name: 'Release'

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  pre-release:
    name: 'Pre-release'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - uses: CupOfTea696/gh-action-auto-release@v1.0.0
        with:
          title: 'Release: $version'
          tag: 'v$semver'
          draft: false
          regex: '/^Release: #{semver}$/i'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
